### ISSUE TITLE
error[E0658]: access to extern crates through prelude is experimental

### ISSUE THREAD

**Issue by asomers** [DonaldWhyte/double#16]
Double does not work on Rust nightly 1.27.0.  Compiling fails with this error:
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
 --> <mock_trait macros>:5:16
  |
5 | $ ( $ method : double :: Mock < ( ( $ ( $ arg_type ) , * ) ) , $ retval > ) ,
  |                ^^^^^^
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable
```
Adding `#![feature(extern_prelude)]`, as suggested, fixes the problem.  However, the crate documentation does not mention this feature.

**Comment by luizdepra** [comment]
Add `use double;` inside your test module.

**Comment by asomers** [comment]
I'm afraid I no longer have a sample of the code that produced this error.  And I can't remember anything about why the code would've worked on 1.26.0 but not 1.27.0.  So I'll just have to close this issue.
